"""The ladder, held to the replay engine tick for tick.

The rule in `journal.live.ladder` is a second implementation of the one in
`frontend/src/lib/replaySim.ts`, and two implementations of one rule is exactly
the "blotter that quietly disagrees with the broker by a rung" hazard that kept
the trail off /live's paper account to begin with. What makes it safe is that the
disagreement is checkable: the fixture is generated by driving the *real* replay
engine (`runSim`, the same entry the Simulator calls) over fixed tapes, and this
replays those tapes through the Python and demands the same stop after every
print.

Regenerate with `tools/ladder-parity/run.sh` when the ladder in `replaySim.ts`
changes on purpose. When it changes by accident, this is the alarm.
"""

from __future__ import annotations

import json
import sys
import threading
import time
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT))

from journal.live.ladder import (LadderRunner, LadderState,  # noqa: E402
                                 TrailCfg, repin, tighten, trail_stop)

FIXTURE = Path(__file__).parent / "fixtures" / "ladder_parity.json"


def _scenarios():
    return json.loads(FIXTURE.read_text())["scenarios"]


def _replay(sc: dict) -> list[float | None]:
    """Walk the scenario's tape exactly as `stepSim` walks it.

    The ORDER IS THE RULE, not an implementation detail of the port:

      1. the drag lands first — `admin(ms)` runs at the top of the tick, before
         anything reads the position;
      2. the bracket is read next (these tapes never reach it, asserted below);
      3. and only then does the high-water mark move and the ladder run, so a
         print can never both set a new best and ratchet a stop into its own path
         on the same tick.

    Get 1 and 3 the wrong way round and the drag scenarios still pass while the
    ordinary ones drift by a rung on the tick a drag happens.
    """
    cfg = TrailCfg.from_ticks(sc["tickSize"], dist=sc["dist"], step=sc["step"],
                              be=sc["be"], be_only=sc["beOnly"])
    assert cfg is not None, "every fixture scenario has a live trail"
    entry = sc["entry"]
    d = 1 if sc["side"] == "long" else -1
    st = LadderState(side=sc["side"], entry_price=entry, cfg=cfg, hwm=entry,
                     # The wide bracket the fixture places, so that "never
                     # loosens" is exercised from a real starting level rather
                     # than from None.
                     stop=entry - d * 500)
    drag = sc["drag"]
    dragged = False
    out: list[float | None] = []
    for i, px in enumerate(sc["prices"]):
        if drag and not dragged and drag["at"] <= i:
            repin(st, drag["stop"])
            dragged = True
        # The exit the fixture is deliberately kept away from. If a tape ever
        # does reach it the comparison below stops meaning what it says, so this
        # is asserted rather than assumed.
        assert (px - st.stop) * d > 0, "fixture tape hit its own stop"
        st.mark(px)
        lvl = trail_stop(st)
        if lvl is not None:
            tighten(st, lvl)
        out.append(st.stop)
    return out


@pytest.mark.parametrize("sc", _scenarios(), ids=lambda s: s["name"])
def test_the_python_ladder_puts_the_stop_where_the_replay_does(sc):
    assert _replay(sc) == sc["stops"]


@pytest.mark.parametrize("sc", _scenarios(), ids=lambda s: s["name"])
def test_the_high_water_mark_agrees_too(sc):
    """The stop is a function of the mark, so a mark that drifts is a stop that
    is about to. Checked separately because the two fail at different times: a
    wrong mark can sit on the same rung for hundreds of prints before it shows
    up in the level."""
    cfg = TrailCfg.from_ticks(sc["tickSize"], dist=sc["dist"], step=sc["step"],
                              be=sc["be"], be_only=sc["beOnly"])
    d = 1 if sc["side"] == "long" else -1
    st = LadderState(side=sc["side"], entry_price=sc["entry"], cfg=cfg,
                     hwm=sc["entry"], stop=sc["entry"] - d * 500)
    drag, dragged, marks = sc["drag"], False, []
    for i, px in enumerate(sc["prices"]):
        if drag and not dragged and drag["at"] <= i:
            repin(st, drag["stop"])
            dragged = True
        st.mark(px)
        lvl = trail_stop(st)
        if lvl is not None:
            tighten(st, lvl)
        marks.append(st.hwm)
    assert marks == sc["hwms"]


# --- the rule in its own right ----------------------------------------------
#
# The fixture proves the two agree. These prove they agree on the *right* thing:
# a docstring that has drifted from the code is worth catching here rather than
# after a live position has trailed somewhere surprising.


def _long(dist=40, step=20, be=4, be_only=False, entry=21000.0):
    cfg = TrailCfg.from_ticks(0.25, dist=dist, step=step, be=be, be_only=be_only)
    return LadderState(side="long", entry_price=entry, cfg=cfg, hwm=entry)


def test_the_worked_example_in_the_docstring_is_true():
    # "with a 40-tick trail, a 20-tick step and a 4-tick breakeven, a long from
    # 21000 puts its stop on 21001 once the trade has printed 21010, on 21006 at
    # 21015" — journal/live/ladder.py and replaySim.ts:419 say the same thing.
    st = _long()
    st.mark(21010)
    assert trail_stop(st) == 21001
    st.mark(21015)
    assert trail_stop(st) == 21006


def test_nothing_happens_until_the_trade_is_far_enough_in_front():
    st = _long()
    st.mark(21009.75)
    assert trail_stop(st) is None


def test_the_trail_is_off_at_zero_distance():
    assert TrailCfg.from_ticks(0.25, dist=0, step=20, be=4) is None


def test_a_breakeven_only_ladder_takes_one_rung_and_stays():
    st = _long(be_only=True)
    st.mark(21010)
    assert trail_stop(st) == 21001
    st.mark(21100)
    assert trail_stop(st) == 21001


def test_step_zero_means_one_rung_per_distance():
    st = _long(step=0, be=0)
    st.mark(21010)
    assert trail_stop(st) == 21000
    st.mark(21019.75)
    assert trail_stop(st) == 21000
    st.mark(21020)
    assert trail_stop(st) == 21010


def test_the_short_side_mirrors_exactly():
    cfg = TrailCfg.from_ticks(0.25, dist=40, step=20, be=4)
    st = LadderState(side="short", entry_price=21000.0, cfg=cfg, hwm=21000.0)
    st.mark(20990)
    assert trail_stop(st) == 20999
    st.mark(20985)
    assert trail_stop(st) == 20994


def test_the_stop_never_loosens():
    st = _long()
    st.stop = 21006
    assert tighten(st, 21001) is False
    assert st.stop == 21006
    # And it reports whether it moved, because the caller is about to spend a
    # wire round trip on the answer.
    assert tighten(st, 21011) is True
    assert st.stop == 21011


def test_a_pullback_does_not_give_a_rung_back():
    st = _long()
    st.mark(21015)
    tighten(st, trail_stop(st))
    assert st.stop == 21006
    st.mark(21005)  # only ever moves the mark forward
    assert st.hwm == 21015
    assert trail_stop(st) == 21006


def test_a_drag_repins_the_grid_and_walks_the_mark_back():
    st = _long()
    st.mark(21020)
    tighten(st, trail_stop(st))
    assert st.stop == 21011
    repin(st, 21014)
    assert st.stop == 21014
    assert st.ladder == 21014
    # The mark walks back to the last high the dragged level is consistent with:
    # 21014 + (40 - 4) ticks = 21023. It was only at 21020, so it stands.
    assert st.hwm == 21020
    # And the rungs from here are spaced off the drag, not off the entry: the
    # next one needs the mark to clear the drag by the ride *plus* a step
    # (21014 + 36t + 20t = 21028), not merely to move.
    st.mark(21025)
    assert trail_stop(st) == 21014
    st.mark(21028)
    assert trail_stop(st) == 21019


def test_a_drag_clears_the_armed_flag():
    """A stop the ladder moved is not the stop you placed, and the blotter says
    which one got you out. A dragged level is yours again until the next rung."""
    st = _long()
    st.mark(21015)
    tighten(st, trail_stop(st))
    assert st.armed is True
    repin(st, 21008)
    assert st.armed is False


def test_the_mark_walks_back_when_the_drag_is_loose_enough_to_need_it():
    st = _long()
    st.mark(21100)
    repin(st, 21002)
    # 21002 + 36 ticks = 21011, well under the 21100 the trade had seen — so the
    # ladder forgets that high rather than snapping straight back through the
    # level just dragged to.
    assert st.hwm == 21011
    assert trail_stop(st) == 21002


def test_the_ladder_is_off_when_the_position_never_goes_in_front():
    st = _long()
    for px in (20999, 20990, 20995, 21000):
        st.mark(px)
        assert trail_stop(st) is None
    assert st.rungs == []


def test_every_level_asked_for_is_recorded_in_order():
    """`rungs` is what `orders.jsonl` gets read against after a live run: a
    ladder that ends in the right place having taken the wrong path is still
    wrong."""
    st = _long()
    for px in (21010, 21015, 21020, 21012, 21025):
        st.mark(px)
        lvl = trail_stop(st)
        if lvl is not None:
            tighten(st, lvl)
    assert st.rungs == [21001, 21006, 21011, 21016]


# --- the ratchet ------------------------------------------------------------
#
# The rule decides where the stop goes; the runner decides when to spend a wire
# round trip saying so, and does it on a thread. What is worth testing here is
# almost entirely the awkward timing: a position that closes while a modify is
# in the air, a plant that refuses, a drag that lands mid-ladder.


class Wire:
    """A stand-in for `Broker.modify`, with a hand on the clock.

    `hold` lets a test park a modify in flight and do something to the position
    underneath it — which is the only way to reach the stale-epoch path
    deliberately rather than by racing.
    """

    def __init__(self, fail_times: int = 0) -> None:
        self.sent: list[float] = []
        self.lines: list[tuple] = []
        self.fail_times = fail_times
        self.hold: threading.Event | None = None
        self.entered = threading.Event()
        self._lock = threading.Lock()

    def move(self, level: float) -> None:
        with self._lock:
            self.sent.append(level)
            failing = self.fail_times > 0
            if failing:
                self.fail_times -= 1
        self.entered.set()
        if self.hold is not None:
            self.hold.wait(timeout=5)
        if failing:
            raise RuntimeError("the order plant said no")

    def log(self, event: str, **fields) -> None:
        with self._lock:
            self.lines.append((event, fields))

    def events(self) -> list[str]:
        with self._lock:
            return [e for e, _ in self.lines]


def _wait_until(pred, timeout=3.0):
    """Poll until `pred`, or fail the test saying what it was still waiting on."""
    end = time.monotonic() + timeout
    while time.monotonic() < end:
        if pred():
            return True
        time.sleep(0.005)
    return False


@pytest.fixture
def runner_and_wire():
    wire = Wire()
    r = LadderRunner(move=wire.move, log=wire.log)
    r.start()
    try:
        yield r, wire
    finally:
        r.stop()


def _arm_long(r, stop=20990.0, entry=21000.0, **kw):
    cfg = TrailCfg.from_ticks(0.25, dist=40, step=20, be=4, **kw)
    r.arm(side="long", entry_price=entry, cfg=cfg, stop=stop)


def test_the_runner_sends_a_rung_when_the_mark_earns_one(runner_and_wire):
    r, wire = runner_and_wire
    _arm_long(r)
    r.on_prices(21010, 21000)
    assert _wait_until(lambda: wire.sent == [21001]), wire.sent
    r.on_prices(21015, 21015)
    assert _wait_until(lambda: wire.sent == [21001, 21006]), wire.sent


def test_it_sends_nothing_until_the_trade_is_far_enough_in_front(runner_and_wire):
    r, wire = runner_and_wire
    _arm_long(r)
    r.on_prices(21009, 20995)
    assert not _wait_until(lambda: wire.sent != [], timeout=0.4)


def test_the_batch_extreme_is_what_counts_not_the_last_print(runner_and_wire):
    """A drain can carry a spike the closing tick does not show. Reading only the
    last price would hand back rungs the trade had earned."""
    r, wire = runner_and_wire
    _arm_long(r)
    # High of 21015, and the batch ends back at 21000.
    r.on_prices(21015, 21000)
    assert _wait_until(lambda: wire.sent == [21006]), wire.sent


def test_a_short_ratchets_downward(runner_and_wire):
    r, wire = runner_and_wire
    cfg = TrailCfg.from_ticks(0.25, dist=40, step=20, be=4)
    r.arm(side="short", entry_price=21000.0, cfg=cfg, stop=21010.0)
    r.on_prices(21000, 20990)
    assert _wait_until(lambda: wire.sent == [20999]), wire.sent


def test_the_stop_is_never_sent_loosening(runner_and_wire):
    r, wire = runner_and_wire
    _arm_long(r)
    r.on_prices(21020, 21000)
    assert _wait_until(lambda: wire.sent == [21011]), wire.sent
    # Price falls a long way back. The mark does not move, so neither does the
    # stop, and nothing is sent.
    r.on_prices(21005, 21001)
    assert not _wait_until(lambda: len(wire.sent) > 1, timeout=0.4)


def test_a_rung_that_lands_after_the_position_closed_is_discarded(runner_and_wire):
    r, wire = runner_and_wire
    wire.hold = threading.Event()
    _arm_long(r)
    r.on_prices(21010, 21000)
    assert _wait_until(lambda: wire.entered.is_set()), "modify never started"
    # The position closes while the modify is in the air — 239 ms is long enough
    # for a stop-out and a re-entry.
    r.disarm()
    wire.hold.set()
    assert _wait_until(lambda: "ladder_stale" in wire.events()), wire.events()
    assert r.snapshot() is None


def test_a_rung_in_flight_does_not_land_on_the_next_position(runner_and_wire):
    r, wire = runner_and_wire
    wire.hold = threading.Event()
    _arm_long(r)
    r.on_prices(21010, 21000)
    assert _wait_until(lambda: wire.entered.is_set())
    # Flat, then straight back in the other way. The old rung must not be
    # applied to this.
    r.disarm()
    cfg = TrailCfg.from_ticks(0.25, dist=40, step=20, be=4)
    r.arm(side="short", entry_price=20900.0, cfg=cfg, stop=20910.0)
    wire.hold.set()
    assert _wait_until(lambda: "ladder_stale" in wire.events())
    snap = r.snapshot()
    assert snap["side"] == "short" and snap["stop"] == 20910.0


def test_a_refused_modify_leaves_the_stop_where_it_was_and_retries():
    wire = Wire(fail_times=1)
    r = LadderRunner(move=wire.move, log=wire.log)
    r.start()
    try:
        _arm_long(r)
        r.on_prices(21010, 21000)
        # It asks again, because as far as this process knows the stop never
        # moved — which is the only assumption that is safe in both directions.
        assert _wait_until(lambda: wire.sent == [21001, 21001]), wire.sent
        assert _wait_until(lambda: r.snapshot()["stop"] == 21001)
    finally:
        r.stop()


def test_it_gives_up_rather_than_hammering_a_wedged_plant():
    wire = Wire(fail_times=99)
    r = LadderRunner(move=wire.move, log=wire.log)
    r.start()
    try:
        _arm_long(r)
        r.on_prices(21010, 21000)
        assert _wait_until(lambda: "ladder_gave_up" in wire.events()), wire.events()
        sent = len(wire.sent)
        assert sent == 3
        # And it stays given up: more prints do not restart the storm.
        r.on_prices(21030, 21020)
        assert not _wait_until(lambda: len(wire.sent) > sent, timeout=0.4)
        assert r.snapshot()["failures"] == 3
    finally:
        r.stop()


def test_a_fresh_position_clears_a_ladder_that_had_given_up():
    wire = Wire(fail_times=3)
    r = LadderRunner(move=wire.move, log=wire.log)
    r.start()
    try:
        _arm_long(r)
        r.on_prices(21010, 21000)
        assert _wait_until(lambda: "ladder_gave_up" in wire.events())
        r.disarm()
        _arm_long(r, entry=21100.0, stop=21090.0)
        r.on_prices(21110, 21100)
        assert _wait_until(lambda: 21101 in wire.sent), wire.sent
    finally:
        r.stop()


def test_a_drag_repins_the_running_ladder(runner_and_wire):
    r, wire = runner_and_wire
    _arm_long(r)
    r.on_prices(21020, 21000)
    assert _wait_until(lambda: wire.sent == [21011]), wire.sent
    # Dragged tighter by hand. The grid re-pins there, so the ladder does not
    # immediately claim the level back.
    r.note_drag(21014)
    assert r.snapshot()["stop"] == 21014
    assert not _wait_until(lambda: len(wire.sent) > 1, timeout=0.4)
    # And the next rung is spaced off the drag: 21014 + 36t + 20t.
    r.on_prices(21028, 21020)
    assert _wait_until(lambda: wire.sent == [21011, 21019]), wire.sent


def test_a_drag_on_nothing_is_a_no_op(runner_and_wire):
    r, _ = runner_and_wire
    r.note_drag(21000)  # flat: there is no ladder to re-pin
    assert r.snapshot() is None


def test_prints_while_flat_are_ignored(runner_and_wire):
    r, wire = runner_and_wire
    r.on_prices(21500, 20500)
    assert wire.sent == []


def test_a_restart_mid_trade_can_seed_the_mark_from_the_tape(runner_and_wire):
    """A process that did not watch the position open rebuilds the mark from the
    session tape, so the ladder comes back where it was rather than starting
    again from the current price."""
    r, wire = runner_and_wire
    cfg = TrailCfg.from_ticks(0.25, dist=40, step=20, be=4)
    r.arm(side="long", entry_price=21000.0, cfg=cfg, stop=20990.0, hwm=21020.0)
    # No new prints at all — the seeded mark alone already earns a rung.
    assert _wait_until(lambda: wire.sent == [21011]), wire.sent


def test_stopping_the_runner_leaves_the_stop_alone(runner_and_wire):
    """The stop is a working order at the broker, not something this process
    holds up. Losing the ratchet is lost tightening, not lost protection."""
    r, wire = runner_and_wire
    _arm_long(r)
    r.on_prices(21020, 21000)
    assert _wait_until(lambda: wire.sent == [21011])
    r.stop()
    r.on_prices(21100, 21050)
    assert not _wait_until(lambda: len(wire.sent) > 1, timeout=0.3)
