"""Regime-vs-P&L scoring: the Python must agree with the browser, to the bit.

The numbers in this module used to live only in frontend/src/lib/regimeStats.ts.
Now they are computed server-side and snapshotted, and the two implementations
have to produce the *same* answer — a permutation p-value that depends on who ran
it is not a p-value, and "the panel says 12% but the file says 14%" is a bug that
would take an afternoon to even notice.

So the fixtures below are golden: generated by running the real TypeScript under
node and freezing what it said. `luck` is the one that matters — it is the only
thing that pins the seeded mulberry32 port and the Fisher-Yates draw order, and a
strong-signal fixture can't test it (luck is 0 there no matter how wrong the RNG
is). Hence NOISE, whose 0.38 is a number only the exact draw sequence produces.

Regenerate (if regimeStats.ts ever legitimately changes):
    node -e 'import("./frontend/src/lib/regimeStats.ts").then(...)'

Run directly:  ``.venv/bin/python tests/test_regime_pnl.py``
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "src"))
sys.path.insert(0, str(ROOT))

from journal.sim import regime_pnl as rp  # noqa: E402

TOL = 1e-9


def _pts(rows):
    return [dict(zip(("date", "x", "net", "trades", "wins"), r)) for r in rows]


# --- golden: a KPI that genuinely tracks P&L (24 days) ----------------------
SIGNAL = _pts([
    ("2025-09-01", 0.20, -61.06, 1, 1), ("2025-09-02", 9.10, 243.01, 1, 0),
    ("2025-09-03", 5.96, 234.68, 4, 0), ("2025-09-04", 9.66, 212.58, 1, 1),
    ("2025-09-05", 3.96, 280.06, 5, 2), ("2025-09-06", 9.94, 247.55, 4, 2),
    ("2025-09-07", 2.87, -242.02, 3, 2), ("2025-09-08", 0.89, -410.16, 5, 1),
    ("2025-09-09", 4.63, 312.57, 2, 1), ("2025-09-10", 0.15, -251.32, 4, 1),
    ("2025-09-11", 9.55, 326.18, 3, 2), ("2025-09-12", 6.23, 259.65, 1, 1),
    ("2025-09-13", 4.57, 160.39, 4, 1), ("2025-09-14", 5.76, -96.02, 4, 2),
    ("2025-09-15", 4.57, 256.42, 4, 2), ("2025-09-16", 3.92, -207.49, 5, 4),
    ("2025-09-17", 6.85, 299.88, 2, 1), ("2025-09-18", 7.97, 111.24, 1, 0),
    ("2025-09-19", 8.75, 48.63, 4, 2), ("2025-09-20", 3.92, -70.13, 5, 4),
    ("2025-09-21", 8.32, 420.11, 4, 2), ("2025-09-22", 6.31, 272.35, 5, 2),
    ("2025-09-23", 8.25, 246.61, 1, 1), ("2025-09-24", 1.12, -349.97, 3, 3),
])
SIGNAL_GOLD = {
    "rho": 0.6054807010367548,
    "edge": 396.0,
    "win_edge": -5.432937181663846,
    "luck": 0.0,
    "days": 24,
}

# --- golden: a KPI that tracks nothing (18 days). The `luck` here is the whole
# point of this file — 0.38 falls out of the exact shuffle sequence and nothing
# else. Get the RNG wrong and this lands somewhere else.
NOISE = _pts([
    ("2025-10-01", 5.37, -56.33, 4, 4), ("2025-10-02", 2.28, -7.29, 3, 1),
    ("2025-10-03", 7.79, 269.30, 1, 0), ("2025-10-04", 6.35, 136.59, 2, 1),
    ("2025-10-05", 7.09, 138.64, 1, 0), ("2025-10-06", 4.99, 372.31, 4, 0),
    ("2025-10-07", 2.30, 103.72, 3, 2), ("2025-10-08", 7.09, 41.75, 4, 4),
    ("2025-10-09", 8.65, 81.05, 3, 3), ("2025-10-10", 1.68, -72.92, 4, 0),
    ("2025-10-11", 3.79, -184.30, 2, 1), ("2025-10-12", 3.37, 339.80, 2, 1),
    ("2025-10-13", 7.37, -204.60, 3, 2), ("2025-10-14", 0.92, -340.15, 4, 4),
    ("2025-10-15", 3.57, 214.53, 1, 0), ("2025-10-16", 8.83, -275.39, 4, 4),
    ("2025-10-17", 6.86, 388.26, 3, 3), ("2025-10-18", 2.16, -332.00, 2, 0),
])
NOISE_GOLD = {
    "rho": 0.22199280191185172,
    "edge": 59.93166666666664,
    "win_edge": 36.80555555555556,
    "luck": 0.38,
    "days": 18,
}


def test_matches_typescript():
    for name, pts, gold in (("SIGNAL", SIGNAL, SIGNAL_GOLD), ("NOISE", NOISE, NOISE_GOLD)):
        s = rp.score(pts)
        for k, want in gold.items():
            got = s[k]
            assert abs(got - want) < TOL, f"{name}.{k}: {got!r} != TS {want!r}"
    print("✓ scores match the TypeScript, luck included")


def test_tied_ranks():
    """Ties share the mean rank, or a KPI that plateaus (an occupancy pinned at 1.0
    for a week) silently scores on the order its days happened to arrive in."""
    got = rp.rank_corr([1, 1, 2, 2, 3, 3], [5, 5, 1, 9, 2, 2])
    assert abs(got - (-0.4923659639173309)) < TOL, got
    print("✓ tie handling matches the TypeScript")


def test_thin_sample_is_none():
    """Under six days a tercile is two days wide: there is nothing to rank, and
    saying so beats returning a confident number computed from four sessions."""
    assert rp.score(SIGNAL[:5]) is None
    assert rp.score(SIGNAL[:6]) is not None
    print("✓ thin samples decline to score")


def test_bands_partition_the_days():
    """Every day lands in exactly one band, and the outer two are what `edge`
    compares — if the bands lost or duplicated a day, `edge` would be quietly wrong
    rather than obviously broken.

    The bands carry no member list (see _band), so membership is checked the way a
    reader has to recover it: by the [lo, hi] value ranges, which must tile the
    days in order without overlapping.
    """
    s = rp.score(SIGNAL)
    lo, mid, hi = s["bands"]
    assert [b["band"] for b in s["bands"]] == ["low", "mid", "high"]
    assert lo["days"] == hi["days"] == len(SIGNAL) // 3
    assert lo["days"] + mid["days"] + hi["days"] == len(SIGNAL)
    assert lo["hi"] <= mid["lo"] and mid["hi"] <= hi["lo"]  # sorted, non-overlapping
    assert lo["lo"] == min(p["x"] for p in SIGNAL)
    assert hi["hi"] == max(p["x"] for p in SIGNAL)
    assert sum(b["trades"] for b in s["bands"]) == sum(p["trades"] for p in SIGNAL)
    assert abs((hi["avg_net"] - lo["avg_net"]) - s["edge"]) < TOL
    print("✓ bands partition the days and reproduce `edge`")


def test_constant_kpi_is_pure_luck():
    """A KPI with the same value every day explains nothing, and must not come back
    as ρ=0 with a suspiciously clean p-value."""
    flat = [{**p, "x": 0.5} for p in SIGNAL]
    s = rp.score(flat)
    assert s["rho"] == 0.0
    assert s["luck"] == 1.0
    print("✓ a constant KPI scores as pure noise")


def test_daily_pnl_rollup():
    """A trade belongs to the session it entered in; a win is a positive *net*
    (after commission), not a positive gross — the rollup the whole study joins on."""
    trades = pd.DataFrame([
        {"session": "2025-09-01", "net_pnl": 100.0},
        {"session": "2025-09-01", "net_pnl": -40.0},
        {"session": "2025-09-01", "net_pnl": 0.0},      # a scratch is not a win
        {"session": "2025-09-02T00:00:00", "net_pnl": 25.0},  # timestamped session
    ])
    by = rp.daily_pnl(trades)
    assert by["2025-09-01"] == {"net": 60.0, "trades": 3, "wins": 1}
    assert by["2025-09-02"] == {"net": 25.0, "trades": 1, "wins": 1}
    assert rp.daily_pnl(pd.DataFrame()) == {}
    print("✓ daily rollup buckets by entry session")


def test_luck_bar_tightens_with_the_family():
    """The bar has to move with how many KPIs were tried, or the board's best row is
    'significant' by construction."""
    assert rp.luck_threshold(20) < rp.luck_threshold(5) < 0.05 + TOL
    assert rp.expected_false_positives(20) == 1.0
    print("✓ the multiple-testing bar tightens with the family size")


if __name__ == "__main__":
    test_matches_typescript()
    test_tied_ranks()
    test_thin_sample_is_none()
    test_bands_partition_the_days()
    test_constant_kpi_is_pure_luck()
    test_daily_pnl_rollup()
    test_luck_bar_tightens_with_the_family()
    print("\nall good")
